version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'banco_produto'
      MYSQL_USER: 'usuario'
      MYSQL_PASSWORD: 'senha'
      MYSQL_ROOT_PASSWORD: 'senha'
    ports:
      - "3306:3306"
